bcftools mpileup -Ou -q 30 -Q 30 -d 500 -f ./results/hybpiper/refs/militaris ./results/mapping/militaris/HY08.uniqueRG.bam \
./results/mapping/militaris/HY13.uniqueRG.bam \
./results/mapping/militaris/HY18.uniqueRG.bam \
./results/mapping/militaris/HY19.uniqueRG.bam \
./results/mapping/militaris/HY30.uniqueRG.bam \
./results/mapping/militaris/HY47.uniqueRG.bam \
./results/mapping/militaris/HY54.uniqueRG.bam \
./results/mapping/militaris/HY58.uniqueRG.bam \
./results/mapping/militaris/HY60.uniqueRG.bam \
./results/mapping/militaris/HY61.uniqueRG.bam \
./results/mapping/militaris/HY80.uniqueRG.bam \
./results/mapping/militaris/HY82.uniqueRG.bam \
./results/mapping/militaris/HY87.uniqueRG.bam \
./results/mapping/militaris/HY92.uniqueRG.bam \
./results/mapping/militaris/HY97.uniqueRG.bam \
./results/mapping/militaris/HY101.uniqueRG.bam \
./results/mapping/militaris/HY102.uniqueRG.bam \
./results/mapping/militaris/HY112.uniqueRG.bam \
./results/mapping/militaris/HY123.uniqueRG.bam \
./results/mapping/militaris/HY144.uniqueRG.bam \
./results/mapping/militaris/HY173.uniqueRG.bam \
./results/mapping/militaris/HY180.uniqueRG.bam \
./results/mapping/militaris/HY189.uniqueRG.bam \
./results/mapping/militaris/HY190.uniqueRG.bam \
./results/mapping/militaris/HY194.uniqueRG.bam \
./results/mapping/militaris/HY211.uniqueRG.bam \
./results/mapping/militaris/HY214.uniqueRG.bam \
./results/mapping/militaris/HY218.uniqueRG.bam \
./results/mapping/militaris/HY219.uniqueRG.bam \
./results/mapping/militaris/HY222.uniqueRG.bam \
./results/mapping/militaris/HY226.uniqueRG.bam \
./results/mapping/militaris/HY227.uniqueRG.bam \
./results/mapping/militaris/HY254.uniqueRG.bam \
./results/mapping/militaris/HY265.uniqueRG.bam \
./results/mapping/militaris/HY268.uniqueRG.bam \
./results/mapping/militaris/HY271.uniqueRG.bam \
./results/mapping/militaris/HY286.uniqueRG.bam \
./results/mapping/militaris/HY288.uniqueRG.bam \
./results/mapping/militaris/HY291.uniqueRG.bam \
./results/mapping/militaris/HY296.uniqueRG.bam \
./results/mapping/militaris/HY300.uniqueRG.bam \
./results/mapping/militaris/HY309.uniqueRG.bam \
./results/mapping/militaris/HY311.uniqueRG.bam \
./results/mapping/militaris/HY312.uniqueRG.bam \
./results/mapping/militaris/HY316.uniqueRG.bam \
./results/mapping/militaris/HY332.uniqueRG.bam \
./results/mapping/militaris/HY337.uniqueRG.bam \
./results/mapping/militaris/HY344.uniqueRG.bam \
./results/mapping/militaris/HY349.uniqueRG.bam \
./results/mapping/militaris/HY355.uniqueRG.bam \
./results/mapping/militaris/HY359.uniqueRG.bam \
./results/mapping/militaris/HY364.uniqueRG.bam \
./results/mapping/militaris/HY371.uniqueRG.bam \
./results/mapping/militaris/HY381.uniqueRG.bam \
./results/mapping/militaris/HY384.uniqueRG.bam \
./results/mapping/militaris/O01.uniqueRG.bam \
./results/mapping/militaris/O12.uniqueRG.bam \
./results/mapping/militaris/O13.uniqueRG.bam \
./results/mapping/militaris/O17.uniqueRG.bam \
./results/mapping/militaris/O21.uniqueRG.bam \
./results/mapping/militaris/O25.uniqueRG.bam \
./results/mapping/militaris/O26.uniqueRG.bam \
./results/mapping/militaris/O29.uniqueRG.bam \
./results/mapping/militaris/O31.uniqueRG.bam \
./results/mapping/militaris/O51.uniqueRG.bam \
./results/mapping/militaris/O53.uniqueRG.bam \
./results/mapping/militaris/O62.uniqueRG.bam \
./results/mapping/militaris/O64.uniqueRG.bam \
./results/mapping/militaris/O71.uniqueRG.bam \
./results/mapping/militaris/O72.uniqueRG.bam \
./results/mapping/militaris/O76.uniqueRG.bam \
./results/mapping/militaris/O80.uniqueRG.bam \
./results/mapping/militaris/O81.uniqueRG.bam \
./results/mapping/militaris/O98.uniqueRG.bam \
./results/mapping/militaris/O106.uniqueRG.bam \
./results/mapping/militaris/O118.uniqueRG.bam \
./results/mapping/militaris/O119.uniqueRG.bam \
./results/mapping/militaris/O120.uniqueRG.bam \
./results/mapping/militaris/O124.uniqueRG.bam \
./results/mapping/militaris/O141.uniqueRG.bam \
./results/mapping/militaris/O148.uniqueRG.bam \
./results/mapping/militaris/O171.uniqueRG.bam \
./results/mapping/militaris/O178.uniqueRG.bam \
./results/mapping/militaris/O184.uniqueRG.bam \
./results/mapping/militaris/O187.uniqueRG.bam \
./results/mapping/militaris/O190.uniqueRG.bam \
./results/mapping/militaris/O193.uniqueRG.bam \
./results/mapping/militaris/O198.uniqueRG.bam \
./results/mapping/militaris/O202.uniqueRG.bam \
./results/mapping/militaris/O203.uniqueRG.bam \
./results/mapping/militaris/O205.uniqueRG.bam \
| bcftools call -mv -Ob -o ./results/known/militaris/calls.bcf

bcftools mpileup -Ou -q 30 -Q 30 -d 500 -f ./results/hybpiper/refs/purpurea \
./results/mapping/purpurea/HY08.uniqueRG.bam \
./results/mapping/purpurea/HY13.uniqueRG.bam \
./results/mapping/purpurea/HY18.uniqueRG.bam \
./results/mapping/purpurea/HY19.uniqueRG.bam \
./results/mapping/purpurea/HY30.uniqueRG.bam \
./results/mapping/purpurea/HY47.uniqueRG.bam \
./results/mapping/purpurea/HY54.uniqueRG.bam \
./results/mapping/purpurea/HY58.uniqueRG.bam \
./results/mapping/purpurea/HY60.uniqueRG.bam \
./results/mapping/purpurea/HY61.uniqueRG.bam \
./results/mapping/purpurea/HY80.uniqueRG.bam \
./results/mapping/purpurea/HY82.uniqueRG.bam \
./results/mapping/purpurea/HY87.uniqueRG.bam \
./results/mapping/purpurea/HY92.uniqueRG.bam \
./results/mapping/purpurea/HY97.uniqueRG.bam \
./results/mapping/purpurea/HY101.uniqueRG.bam \
./results/mapping/purpurea/HY102.uniqueRG.bam \
./results/mapping/purpurea/HY112.uniqueRG.bam \
./results/mapping/purpurea/HY123.uniqueRG.bam \
./results/mapping/purpurea/HY144.uniqueRG.bam \
./results/mapping/purpurea/HY173.uniqueRG.bam \
./results/mapping/purpurea/HY180.uniqueRG.bam \
./results/mapping/purpurea/HY189.uniqueRG.bam \
./results/mapping/purpurea/HY190.uniqueRG.bam \
./results/mapping/purpurea/HY194.uniqueRG.bam \
./results/mapping/purpurea/HY211.uniqueRG.bam \
./results/mapping/purpurea/HY214.uniqueRG.bam \
./results/mapping/purpurea/HY218.uniqueRG.bam \
./results/mapping/purpurea/HY219.uniqueRG.bam \
./results/mapping/purpurea/HY222.uniqueRG.bam \
./results/mapping/purpurea/HY226.uniqueRG.bam \
./results/mapping/purpurea/HY227.uniqueRG.bam \
./results/mapping/purpurea/HY254.uniqueRG.bam \
./results/mapping/purpurea/HY265.uniqueRG.bam \
./results/mapping/purpurea/HY268.uniqueRG.bam \
./results/mapping/purpurea/HY271.uniqueRG.bam \
./results/mapping/purpurea/HY286.uniqueRG.bam \
./results/mapping/purpurea/HY288.uniqueRG.bam \
./results/mapping/purpurea/HY291.uniqueRG.bam \
./results/mapping/purpurea/HY296.uniqueRG.bam \
./results/mapping/purpurea/HY300.uniqueRG.bam \
./results/mapping/purpurea/HY309.uniqueRG.bam \
./results/mapping/purpurea/HY311.uniqueRG.bam \
./results/mapping/purpurea/HY312.uniqueRG.bam \
./results/mapping/purpurea/HY316.uniqueRG.bam \
./results/mapping/purpurea/HY332.uniqueRG.bam \
./results/mapping/purpurea/HY337.uniqueRG.bam \
./results/mapping/purpurea/HY344.uniqueRG.bam \
./results/mapping/purpurea/HY349.uniqueRG.bam \
./results/mapping/purpurea/HY355.uniqueRG.bam \
./results/mapping/purpurea/HY359.uniqueRG.bam \
./results/mapping/purpurea/HY364.uniqueRG.bam \
./results/mapping/purpurea/HY371.uniqueRG.bam \
./results/mapping/purpurea/HY381.uniqueRG.bam \
./results/mapping/purpurea/HY384.uniqueRG.bam \
./results/mapping/purpurea/O01.uniqueRG.bam \
./results/mapping/purpurea/O12.uniqueRG.bam \
./results/mapping/purpurea/O13.uniqueRG.bam \
./results/mapping/purpurea/O17.uniqueRG.bam \
./results/mapping/purpurea/O21.uniqueRG.bam \
./results/mapping/purpurea/O25.uniqueRG.bam \
./results/mapping/purpurea/O26.uniqueRG.bam \
./results/mapping/purpurea/O29.uniqueRG.bam \
./results/mapping/purpurea/O31.uniqueRG.bam \
./results/mapping/purpurea/O51.uniqueRG.bam \
./results/mapping/purpurea/O53.uniqueRG.bam \
./results/mapping/purpurea/O62.uniqueRG.bam \
./results/mapping/purpurea/O64.uniqueRG.bam \
./results/mapping/purpurea/O71.uniqueRG.bam \
./results/mapping/purpurea/O72.uniqueRG.bam \
./results/mapping/purpurea/O76.uniqueRG.bam \
./results/mapping/purpurea/O80.uniqueRG.bam \
./results/mapping/purpurea/O81.uniqueRG.bam \
./results/mapping/purpurea/O98.uniqueRG.bam \
./results/mapping/purpurea/O106.uniqueRG.bam \
./results/mapping/purpurea/O118.uniqueRG.bam \
./results/mapping/purpurea/O119.uniqueRG.bam \
./results/mapping/purpurea/O120.uniqueRG.bam \
./results/mapping/purpurea/O124.uniqueRG.bam \
./results/mapping/purpurea/O141.uniqueRG.bam \
./results/mapping/purpurea/O148.uniqueRG.bam \
./results/mapping/purpurea/O171.uniqueRG.bam \
./results/mapping/purpurea/O178.uniqueRG.bam \
./results/mapping/purpurea/O184.uniqueRG.bam \
./results/mapping/purpurea/O187.uniqueRG.bam \
./results/mapping/purpurea/O190.uniqueRG.bam \
./results/mapping/purpurea/O193.uniqueRG.bam \
./results/mapping/purpurea/O198.uniqueRG.bam \
./results/mapping/purpurea/O202.uniqueRG.bam \
./results/mapping/purpurea/O203.uniqueRG.bam \
./results/mapping/purpurea/O205.uniqueRG.bam \
| bcftools call -mv -Ob -o ./results/known/purpurea/calls.bcf

