#!/bin/bash
#
#SBATCH --chdir=/data/projects/gargiulo_popgen/Leif
#SBATCH --job-name=map
#SBATCH --error=/data/projects/gargiulo_popgen/Leif/errorM.txt
#SBATCH --output=/data/projects/gargiulo_popgen/Leif/outM.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mem-per-cpu=8000
#SBATCH --partition=short
echo "hello world!"

module load bwa/0.7.17 samtools/1.13 

for sample in `cat samplelist.txt`
  do bwa mem -M -t 10 \
   ./results/hybpiper/refs/militaris \
   ./data/${sample}_1.fastq \
   ./data/${sample}_2.fastq | samtools view -b -h -S > results/mapping/militaris/${sample}.bam
done
